### ISSUE TITLE
README link to PORN

### ISSUE THREAD

**Issue by HudsonAfonso** [davydovanton/stop_active_support_anywhere#29]
"Cutting Corners or Why Rails May Kill Ruby by @solnic"
http://solnic.eu/2015/06/06/cutting-corners-or-why-rails-may-kill-ruby.html == PORN

correct link
https://solnic.codes/2015/06/06/cutting-corners-or-why-rails-may-kill-ruby/

**Comment by davydovanton** [comment]
thansk for the report! could you prepare a PR with this changes?

**Comment by solnic** [comment]
Not sure why this was closed but #36 fixes it + updates another link to Avdi's article. Sorry for the trouble 😓
