### ISSUE TITLE
Goal is clearly stated, but ...

### ISSUE THREAD

**Issue by igneus** [davydovanton/stop_active_support_anywhere#3]
... not it's value: why should it be better to depend on Hashie rather than ActiveSupport when you need hash with indifferent access? ... It's definitely worth explaining in the README.

**Comment by davydovanton** [comment]
@igneus, thanks for this issue 👍 
Now I have three goals in my mind:
1. collect all gems or solutions which can replace some parts of AS (current status)
2. filter all this information (drop unnecessary like Hashie, for example)
3. create list of not only rails gems which use AS and try to fix it 

As you can see I'm on the first step. And I'll be super happy if you help me with other examples of hash with different access 👏

**Comment by davydovanton** [comment]
oh, I checked hashie gem and found AS dependency 😞 
I'll drop this gem from the list.

Can I close this issue, WDYT?

**Comment by igneus** [comment]
Now I see I wasn't clear enough when explaining my intent: it looks like the issue is about Hashie, but it's not - Hashie was meant only as an example. (And I had no idea that it depends on ActiveSupport.)

I wanted to point out that you declare a goal

> the main idea of this repo is to collect all libraries which you can use instead using ActiveSupport

but you don't explain the motivation behind it. Why is it bad for a general (i.e. not rails-specific) gem to depend on ActiveSupport?

I myself see only one good reason to avoid depending on ActiveSupport: it's shameless monkey-patching of core classes. On the other hand, such monkey-patching sort of belongs to the (Smalltalk and) Ruby programming culture.

**Comment by davydovanton** [comment]
hm, now I see what you want to say.

In general you right, we need to explain the motivation behind it. And also we need to create rules for "bad"/"good" solutions, I think it will be helpful for us in future

**Comment by ivan-kolmychek** [comment]
> On the other hand, such monkey-patching sort of belongs to the (Smalltalk and) Ruby programming culture.

I hope that, given there are a lot of people and posts arguing that we should use it only when strictly necessary and why it's bad, this will change over time.

Now Ruby also has [Refinements](https://ruby-doc.org/core-2.4.0/doc/syntax/refinements_rdoc.html) as a tool for "local" monkey-patching; it helpes to limit the impact in cases where monkey-patching is required.

Basically, going to the famous "sharp knives" analogy, knowing your way around it and using it on small amount of objects that belong to you (i.e. food) is OK, but running around and cutting anything/everything you want is not. :)

**Comment by palkan** [comment]
> 3. create list of not only rails gems which use AS and try to fix it

IMO that should be the main goal of this StopActiveSupport campaign.

Btw, what about calling it "ActiveSupport Responsibly!"? Sounds less inflammatory.

**Comment by igneus** [comment]
As far as I am concerned, the issue can be closed - it has been addressed in #7 . It should be noted, though, that by #7 I've made tone of the README rather more than less "inflammatory".

**Comment by davydovanton** [comment]
agree, let's close it 👍
